#!/bin/bash

# the folder where we record our stuff
RECORD_FOLDER="$HOME"

# The file template defines the beginning of the file
FILE_TEMPLATE="cli_session"

TIMESTAMP="$(date +%F)_$( date +%H-%M)"
echo "I will start recording what you type now."

script --timing=${RECORD_FOLDER}/${FILE_TEMPLATE}_${TIMESTAMP}_timing.log ${RECORD_FOLDER}/${FILE_TEMPLATE}_${TIMESTAMP}_output.log 
